Login e Criar conta
fehferreira/fmu-job-portal pull request #3
Opened 2023-04-26 21:27 UTC by Gustavo0033

Telas de Login e de Cadastro para novas contas

2023-04-26 21:27 UTC, Gustavo0033 commented
Login e Cadastro

2023-05-21 20:21 UTC, Trajy commented
Teste

2023-05-21 20:22 UTC, fehferreira commented
teste

2023-05-21 20:25 UTC, fehferreira requested changes

2023-05-21 20:25 UTC, fehferreira commented on css/Login/login.css
> +div {
Nao é legal colocar propriedades direto em tag, a nao ser que ela esteja em uma condicional dentro de uma classe. Por exemplo

`.classe-exemplo > h1 {
    width: 100%
 }
`

Neste exemplo todos os H1's dentro do elemento com a classe "classe-exemplo" vao ter essa propriedade.

2023-05-21 20:25 UTC, fehferreira commented on html/tela-cadastroConta/criarConta.html
> +
Seria legal, c vc estiver usando o VSCode, instalar a extensao Prettier pra ele formatar os htmls e tirar os espaços em branco

2023-05-21 20:25 UTC, fehferreira commented on html/tela-cadastroConta/criarConta.html
> +        <!-- <img src="../assets/person.png"  class="person" /> -->
Limpar os comentarios que vc nao esta utilizando

2023-05-21 20:25 UTC, fehferreira commented on html/tela-cadastroConta/criarConta.html
> +<script>
Extrair o script para um arquivo .js e importar ele

2023-05-21 20:25 UTC, fehferreira commented on html/tela-cadastroConta/criarConta.html
> +<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
Mudar lang para lang=pt-BR

2023-05-21 23:00 UTC, closed without merging